### ISSUE TITLE
What purposes does `DEBIAN_SOURCE` have and how does it differ to `SOURCE_NAME`?

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#10]
What purposes does `DEBIAN_SOURCE` have and how does it differ to `SOURCE_NAME`

In `build_pkg.yml` and in `build_source` we have both `DEBIAN_SOURCE` and `SOURCE_NAME`. Do not know if this is necessary to have. Can we skip them?

_Originally posted by @nanory in https://github.com/gardenlinux/package-build/pull/8#discussion_r1386050871_

**Comment by alee-cd** [comment]
Not we implement in the way if `debian/` directory available. Use rsync to overwrite to the extracted source directory:
https://github.com/gardenlinux/package-build/pull/8/commits/36afb40d73338a4f495cd6b392a3aab423f566fd

**Comment by alee-cd** [comment]
It passed the tests:
https://github.com/gardenlinux/package-iproute2/actions/runs/6826370144/job/18566170056#step:7:252

**Comment by nanory** [comment]
Having this two parameters gives us more flexibility. You can have the sources from git but still use the debian folder from Debian, if a package exists in Debian but is outdated for example and you want to use the newest sources from Git instead.

For this reason, we need both parameters and we can close this issue.
