### ISSUE TITLE
Add rsync Package to Container Images for improved debian/ merge

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#17]
**What would you like to be added**:

Added `rsync` package installed inside the container image. So that we can use the same `rsync` method to merge `debian/` instead of replace `debian/`.

**Why is this needed**:
To enhance the merging process of the `debian/` directory, it is proposed to include the `rsync` package inside the container images. This addition will allow us to utilize the `rsync` method for merging the `debian/` directory, rather than replacing it entirely. This will be reducing the need for complete `debian/` replacements and minimizing unnecessary file changes in `debian/`.

This is required for #14.

**Comment by nanory** [comment]
Since we won't do the merging as suggested in #14, we don't need this issue here either. I'm closing this.
