### ISSUE TITLE
Enhance document for building container image and packages for local development

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#19]
**What would you like to be added**:

I would like to enhance the existing document to include instructions for building container images locally and generating packages using the container image.

**Why is this needed**:

This update is necessary because the current document lacks certain steps and details required for developers to successfully build container images and generate packages. By providing comprehensive instructions, developers will have a clearer understanding of the process and can effectively build container images and generate packages for local development purposes.

**Comment by Vincinator** [comment]
Thanks! Could you add some requirements to this issue? Please correct me if I am wrong, but it looks like you already encountered some issues. Maybe you can share those issues and we can enhance the documentation accordingly.

**Comment by alee-cd** [comment]
There are some steps are missing in the document. I have draft one on https://github.com/gardenlinux/package-build/pull/20

Please review. :)
