### ISSUE TITLE
Add support for native package builds to the build container

### ISSUE THREAD

**Issue by nanory** [gardenlinux/backup_package-build#2]
**What would you like to be added**:
We should extend the container build with a possibility to build native Debian packages. One would use native Debian packages if they are the maintainer of the upstream source code. There is then no need to pull external source code but the original source code can already been placed in the package repo.

For this however, the build container and its scripts must support native builds. As of now, they only support builds based on sources coming from Debian testing or other Git repos.

**Why is this needed**:
There are some Garden Linux packages which are not build out of external sources but are build with locally stored sources like this one: https://gitlab.com/gardenlinux/gardenlinux-package-gardenlinux-selinux-module

For those cases, we must be able to build Debian native packages which basically already include the upstream code.

**Comment by alee-cd** [comment]
Update the title to `native package builds` to avoid mistake. :)
