### ISSUE TITLE
Skipped Garden Linux packages while migration

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#27]
**What would you like to be added**:

Just put a note to track the skipped package while migration from gitlb:
* anything in Garden Linux legacy packages
* anything in Garden Linux Driver
* Garden Linux package build
* Garden Linux package gitlab-runner
* Garden Linux package linux-tdx
* Garden Linux package linux
* Garden Linux package linux-5.15
* Garden Linux package linux-6.1
* Garden Linux package metabond

**Why is this needed**:
Avoid forgetting.

**Comment by nanory** [comment]
This package explains what package repos haven't been migrated from Gitlab after discussing them with the Garden Linux maintainers like @Vincinator 

I'm closing this issue
