### ISSUE TITLE
The `get_version()` function in `build_source` script should be extended to know the latest upstream from git tag

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#30]
**What would you like to be added**:

I would like to extend the get_version() function in the build_source script to fetch the latest upstream version from git tags when using git as the upstream source.

**Why is this needed**:

After investigated on #29 , 
it has been identified that the --create --package $name command results in a version string of gardenlinux~$commit-hash, for example:
```
+ dch --create --package aws-sdk-cpp --newversion gardenlinux~45805daa1be4515729a226b037e00a726076bb90 --distribution gardenlinux --force-distribution -- 'Rebuild for Garden Linux.' 
```

To improve the versioning process, it is necessary to modify the get_version() function to fetch the latest upstream version from git tags. This will ensure more accurate and meaningful versioning for the packages.

**Comment by nanory** [comment]
This task has been completed by #37 
I'm closing this issue.
