### ISSUE TITLE
restructured crossbuild containerfile hides segfault

### ISSUE THREAD

**Issue by nkraetzschmar** [gardenlinux/backup_package-build#51]
#4 restructured the containerfile and moved the `gcc` sanity check before the import of native binaries. Therefore, the sanity check became ineffective as it now only checks the non native optimised versions.
In fact this change has already hidden a bug causing gcc to segfault when building amd64 targets on an aarch64 host. (the bug is likely caused by some updates to gcc resulting in a binary layout that `patchelf` does not handle correctly when replacing needed libs)

we should:
- fix the containerfile to perform gcc sanity checks **after** importing native accelerated executables
- investigate and fix the segfault in the patched gcc

**Comment by alee-cd** [comment]
Here is a small PR that fix the container file to perform gcc sanity checks after importing native accelerated executables:
https://github.com/gardenlinux/package-build/pull/52

Do you have more info on the segfault in the patched gcc?

**Comment by alee-cd** [comment]
Request technical sponsor from @waldiTM  :)
