### ISSUE TITLE
Compilation Failure for `package-aws-kms-pkcs11` and `package-libstoragemgmt` on arm cross container

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#59]
**What happened**:
The C++ compilation process appears to be malfunctioning, resulting in the failure to build the `package-aws-kms-pkcs11` #48 and `package-libstoragemgmt` #49  packages within the arm cross container.

**What you expected to happen**:
The packages should be successfully built without any errors.

**How to reproduce it (as minimally and precisely as possible)**:
1. Trigger the `build.yml` action workflow on these packages.
2. Check the build results on cross arm container.

**Anything else we need to know**:
The two packages build successfully when compiled natively on arm.

**Environment**:
The issue was tested and cannot be reproduced natively in a local build environment using podman arm64 container on an M1 machine.

**Comment by nanory** [comment]
The corresponding bug has been fixed. The ARM build for `package-aws-kmw-pkcs11` and `pacakge_libstoragemgmt` is working now.
