### ISSUE TITLE
We shouldn't split the version into `SOURCE_VERSION` and `VERSION_SUFFIX`.

### ISSUE THREAD

**Issue by alee-cd** [gardenlinux/backup_package-build#9]
We shouldn't split the version into `SOURCE_VERSION` and `VERSION_SUFFIX` but we should only pass one version to the container and its build script should do the splitting if needed. This way, we can directly pass the git tag to the corresponding Github Action workflow without splitting it beforehand. It's then easier for other package repos (e.g. package-htop) to just pass their Git Tag to `package-build`

_Originally posted by @nanory in https://github.com/gardenlinux/package-build/pull/8#discussion_r1386060206_

**Comment by nanory** [comment]
This has been adjusted in #5, so I'm closing this issue here.
